// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbkypgtpplgrnmkrwmjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtia3lwZ3RwcGxncm5ta3J3bWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzM0MDIsImV4cCI6MjA2MzQwOTQwMn0.VQyhV4Vu_Pl3rolEUsaRMM3PTYwdIZD90j98IM-MleI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);